### ISSUE TITLE
Document Social Media Login

### ISSUE THREAD

**Issue by tacman** [msgphp/symfony-demo-app#117]
I'm a little confused about how to configure logging in with Google and Facebook.  

If I deploy this on Heroku, can you help with the configuration?  I realize this might be more a HWIO issue than msgphp/user-bundle, but the endpoints (on the FB/Google app setup pages) and yaml file (security, etc.) are confusing.

Or if you add a link to an article / tutorial about this.

**Comment by ro0NL** [comment]
Sorry, definitively a HWIO issue :} or at least this issue is way to abstract.

in general, i followed the docs from https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/resource_owners/google.md + https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/3-configuring_the_security_layer.md

i use my personal account at https://console.developers.google.com/ to manage the client keys

i link users with social IDs here https://github.com/msgphp/symfony-demo-app/blob/master/src/Security/OauthUserProvider.php#L24 (this links them based on attribute values, a more simple implementation could be based on a user property)
